<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXhVx8uS\Eccube_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXhVx8uS/Eccube_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXhVx8uS.legacy');

    return;
}

if (!\class_exists(Eccube_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXhVx8uS\Eccube_KernelProdContainer::class, Eccube_KernelProdContainer::class, false);
}

return new \ContainerXhVx8uS\Eccube_KernelProdContainer([
    'container.build_hash' => 'XhVx8uS',
    'container.build_id' => '066a71a0',
    'container.build_time' => 1733815935,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXhVx8uS');
