<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ozl91FTService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ozl91FT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ozl91FT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Delivery' => ['privates', '.errored..service_locator.ozl91FT.Eccube\\Entity\\Delivery', NULL, 'Cannot autowire service ".service_locator.ozl91FT": it needs an instance of "Eccube\\Entity\\Delivery" but this type has been excluded in "eccube/services.yaml".'],
        ], [
            'Delivery' => 'Eccube\\Entity\\Delivery',
        ]);
    }
}
