<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CrUF7WRService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.crUF7WR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.crUF7WR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ProductStatus' => ['privates', '.errored..service_locator.crUF7WR.Eccube\\Entity\\Master\\ProductStatus', NULL, 'Cannot autowire service ".service_locator.crUF7WR": it needs an instance of "Eccube\\Entity\\Master\\ProductStatus" but this type has been excluded in "eccube/services.yaml".'],
            'cacheUtil' => ['privates', 'Eccube\\Util\\CacheUtil', 'getCacheUtilService', true],
        ], [
            'ProductStatus' => 'Eccube\\Entity\\Master\\ProductStatus',
            'cacheUtil' => 'Eccube\\Util\\CacheUtil',
        ]);
    }
}
