<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G3AGa5KService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.g3AGa5K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.g3AGa5K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Shipping' => ['privates', '.errored..service_locator.g3AGa5K.Eccube\\Entity\\Shipping', NULL, 'Cannot autowire service ".service_locator.g3AGa5K": it needs an instance of "Eccube\\Entity\\Shipping" but this type has been excluded in "eccube/services.yaml".'],
        ], [
            'Shipping' => 'Eccube\\Entity\\Shipping',
        ]);
    }
}
