<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1IoPp_AService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.1IoPp.A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1IoPp.A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Mail' => ['privates', '.errored..service_locator.1IoPp.A.Eccube\\Entity\\MailTemplate', NULL, 'Cannot autowire service ".service_locator.1IoPp.A": it needs an instance of "Eccube\\Entity\\MailTemplate" but this type has been excluded in "eccube/services.yaml".'],
        ], [
            'Mail' => 'Eccube\\Entity\\MailTemplate',
        ]);
    }
}
