<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2J24TGzService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.2J24TGz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2J24TGz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'pluginService' => ['services', 'Eccube\\Service\\PluginService', 'getPluginServiceService', true],
            'systemService' => ['services', 'Eccube\\Service\\SystemService', 'getSystemServiceService', false],
        ], [
            'dispatcher' => '?',
            'pluginService' => 'Eccube\\Service\\PluginService',
            'systemService' => 'Eccube\\Service\\SystemService',
        ]);
    }
}
