<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GjkCWvnService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.gjkCWvn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gjkCWvn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Order' => ['privates', '.errored..service_locator.gjkCWvn.Eccube\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.gjkCWvn": it needs an instance of "Eccube\\Entity\\Order" but this type has been excluded in "eccube/services.yaml".'],
        ], [
            'Order' => 'Eccube\\Entity\\Order',
        ]);
    }
}
