<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xnc3VzyService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.xnc3Vzy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xnc3Vzy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['privates', '.errored..service_locator.xnc3Vzy.Doctrine\\ORM\\EntityManager', NULL, 'Cannot autowire service ".service_locator.xnc3Vzy": it references class "Doctrine\\ORM\\EntityManager" but no such service exists. Try changing the type-hint to "Doctrine\\ORM\\EntityManagerInterface" instead.'],
        ], [
            'em' => 'Doctrine\\ORM\\EntityManager',
        ]);
    }
}
