<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ErJVMZFService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ErJVMZF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ErJVMZF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Member' => ['privates', '.errored..service_locator.ErJVMZF.Eccube\\Entity\\Member', NULL, 'Cannot autowire service ".service_locator.ErJVMZF": it needs an instance of "Eccube\\Entity\\Member" but this type has been excluded in "eccube/services.yaml".'],
        ], [
            'Member' => 'Eccube\\Entity\\Member',
        ]);
    }
}
