<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JwY9PZbService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.JwY9PZb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JwY9PZb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Block' => ['privates', '.errored..service_locator.JwY9PZb.Eccube\\Entity\\Block', NULL, 'Cannot autowire service ".service_locator.JwY9PZb": it needs an instance of "Eccube\\Entity\\Block" but this type has been excluded in "eccube/services.yaml".'],
            'cacheUtil' => ['privates', 'Eccube\\Util\\CacheUtil', 'getCacheUtilService', true],
            'fs' => ['privates', 'filesystem', 'getFilesystemService', true],
        ], [
            'Block' => 'Eccube\\Entity\\Block',
            'cacheUtil' => 'Eccube\\Util\\CacheUtil',
            'fs' => '?',
        ]);
    }
}
