<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MvEXitCService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.mvEXitC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mvEXitC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'News' => ['privates', '.errored..service_locator.mvEXitC.Eccube\\Entity\\News', NULL, 'Cannot autowire service ".service_locator.mvEXitC": it needs an instance of "Eccube\\Entity\\News" but this type has been excluded in "eccube/services.yaml".'],
            'cacheUtil' => ['privates', 'Eccube\\Util\\CacheUtil', 'getCacheUtilService', true],
        ], [
            'News' => 'Eccube\\Entity\\News',
            'cacheUtil' => 'Eccube\\Util\\CacheUtil',
        ]);
    }
}
