<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KB_4_GtService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.kB.4.gt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kB.4.gt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'CustomerAddress' => ['privates', '.errored..service_locator.kB.4.gt.Eccube\\Entity\\CustomerAddress', NULL, 'Cannot autowire service ".service_locator.kB.4.gt": it needs an instance of "Eccube\\Entity\\CustomerAddress" but this type has been excluded in "eccube/services.yaml".'],
        ], [
            'CustomerAddress' => 'Eccube\\Entity\\CustomerAddress',
        ]);
    }
}
