<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RYPHD9ZService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.RYPHD9Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RYPHD9Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'TargetPayment' => ['privates', '.errored..service_locator.RYPHD9Z.Eccube\\Entity\\Payment', NULL, 'Cannot autowire service ".service_locator.RYPHD9Z": it needs an instance of "Eccube\\Entity\\Payment" but this type has been excluded in "eccube/services.yaml".'],
        ], [
            'TargetPayment' => 'Eccube\\Entity\\Payment',
        ]);
    }
}
