<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EJRGBpiService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.eJRGBpi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eJRGBpi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'CsvType' => ['privates', '.errored..service_locator.eJRGBpi.Eccube\\Entity\\Master\\CsvType', NULL, 'Cannot autowire service ".service_locator.eJRGBpi": it needs an instance of "Eccube\\Entity\\Master\\CsvType" but this type has been excluded in "eccube/services.yaml".'],
        ], [
            'CsvType' => 'Eccube\\Entity\\Master\\CsvType',
        ]);
    }
}
