<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BA8prNVService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.bA8prNV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bA8prNV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Tag' => ['privates', '.errored..service_locator.bA8prNV.Eccube\\Entity\\Tag', NULL, 'Cannot autowire service ".service_locator.bA8prNV": it needs an instance of "Eccube\\Entity\\Tag" but this type has been excluded in "eccube/services.yaml".'],
        ], [
            'Tag' => 'Eccube\\Entity\\Tag',
        ]);
    }
}
