<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O2Zk3ENService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.O2Zk3EN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O2Zk3EN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Product' => ['privates', '.errored..service_locator.O2Zk3EN.Eccube\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.O2Zk3EN": it needs an instance of "Eccube\\Entity\\Product" but this type has been excluded in "eccube/services.yaml".'],
            'cacheUtil' => ['privates', 'Eccube\\Util\\CacheUtil', 'getCacheUtilService', true],
        ], [
            'Product' => 'Eccube\\Entity\\Product',
            'cacheUtil' => 'Eccube\\Util\\CacheUtil',
        ]);
    }
}
