<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0quxlUuService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.0quxlUu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0quxlUu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Template' => ['privates', '.errored..service_locator.0quxlUu.Eccube\\Entity\\Template', NULL, 'Cannot autowire service ".service_locator.0quxlUu": it needs an instance of "Eccube\\Entity\\Template" but this type has been excluded in "eccube/services.yaml".'],
        ], [
            'Template' => 'Eccube\\Entity\\Template',
        ]);
    }
}
