<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YUJdnI_Service extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.yUJdnI.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yUJdnI.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Calendar' => ['privates', '.errored..service_locator.yUJdnI..Eccube\\Entity\\Calendar', NULL, 'Cannot autowire service ".service_locator.yUJdnI.": it needs an instance of "Eccube\\Entity\\Calendar" but this type has been excluded in "eccube/services.yaml".'],
        ], [
            'Calendar' => 'Eccube\\Entity\\Calendar',
        ]);
    }
}
