<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerAddressService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.kB.4.gt.Eccube\Entity\CustomerAddress' shared service.
     *
     * @return \Eccube\Entity\CustomerAddress
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.kB.4.gt": it needs an instance of "Eccube\\Entity\\CustomerAddress" but this type has been excluded in "eccube/services.yaml".');
    }
}
