<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCacheUtilService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private 'Eccube\Util\CacheUtil' shared autowired service.
     *
     * @return \Eccube\Util\CacheUtil
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Eccube/Util/CacheUtil.php';

        return $container->privates['Eccube\\Util\\CacheUtil'] = new \Eccube\Util\CacheUtil(($container->services['kernel'] ?? $container->get('kernel', 1)), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cache.default_clearer' => ['services', 'cache.app_clearer', 'getCache_AppClearerService', true],
            'cache.global_clearer' => ['services', 'cache.global_clearer', 'getCache_GlobalClearerService', true],
            'cache.system_clearer' => ['services', 'cache.system_clearer', 'getCache_SystemClearerService', true],
        ], [
            'cache.default_clearer' => '?',
            'cache.global_clearer' => 'Symfony\\Component\\HttpKernel\\CacheClearer\\Psr6CacheClearer',
            'cache.system_clearer' => 'Symfony\\Component\\HttpKernel\\CacheClearer\\Psr6CacheClearer',
        ]));
    }
}
