<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsvTypeService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.eJRGBpi.Eccube\Entity\Master\CsvType' shared service.
     *
     * @return \Eccube\Entity\Master\CsvType
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.eJRGBpi": it needs an instance of "Eccube\\Entity\\Master\\CsvType" but this type has been excluded in "eccube/services.yaml".');
    }
}
