<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerRepositoryService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private 'Eccube\Repository\CustomerRepository' shared autowired service.
     *
     * @return \Eccube\Repository\CustomerRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Eccube/Repository/CustomerRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['Eccube\\Repository\\CustomerRepository'])) {
            return $container->privates['Eccube\\Repository\\CustomerRepository'];
        }

        return $container->privates['Eccube\\Repository\\CustomerRepository'] = new \Eccube\Repository\CustomerRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->privates['Eccube\\Doctrine\\Query\\Queries'] ??= new \Eccube\Doctrine\Query\Queries()), $a, ($container->privates['Eccube\\Repository\\OrderRepository'] ?? self::getOrderRepositoryService($container)), ($container->services['Eccube\\Common\\EccubeConfig'] ?? self::getEccubeConfigService($container)));
    }
}
