<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassNameService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.ch9bRtU.Eccube\Entity\ClassName' shared service.
     *
     * @return \Eccube\Entity\ClassName
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ch9bRtU": it needs an instance of "Eccube\\Entity\\ClassName" but this type has been excluded in "eccube/services.yaml".');
    }
}
