<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEccube_Purchase_Flow_Item_Holder_Validator_Empty_Items_ValidatorService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private 'eccube.purchase.flow.item.holder.validator.empty.items.validator' shared service.
     *
     * @return \Eccube\Service\PurchaseFlow\Processor\EmptyItemsValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Eccube/Service/PurchaseFlow/ValidatorTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Eccube/Service/PurchaseFlow/ItemHolderValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Eccube/Service/PurchaseFlow/Processor/EmptyItemsValidator.php';

        return $container->privates['eccube.purchase.flow.item.holder.validator.empty.items.validator'] = new \Eccube\Service\PurchaseFlow\Processor\EmptyItemsValidator(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
