<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEccube_Purchase_Flow_Discount_Processor_Point_ProcessorService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private 'eccube.purchase.flow.discount.processor.point.processor' shared service.
     *
     * @return \Eccube\Service\PurchaseFlow\Processor\PointProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Eccube/Service/PurchaseFlow/DiscountProcessor.php';
        include_once \dirname(__DIR__, 4).'/src/Eccube/Service/PurchaseFlow/PurchaseProcessor.php';
        include_once \dirname(__DIR__, 4).'/src/Eccube/Service/PurchaseFlow/Processor/PointProcessor.php';

        return $container->privates['eccube.purchase.flow.discount.processor.point.processor'] = new \Eccube\Service\PurchaseFlow\Processor\PointProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['Eccube\\Service\\PointHelper'] ?? $container->load('getPointHelperService')));
    }
}
