<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLayoutService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.DWb.ZZ6.Eccube\Entity\Layout' shared service.
     *
     * @return \Eccube\Entity\Layout
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.DWb.ZZ6": it needs an instance of "Eccube\\Entity\\Layout" but this type has been excluded in "eccube/services.yaml".');
    }
}
