<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonolog_Handler_EUserDeprecatedFilterService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private 'monolog.handler.e_user_deprecated_filter' shared service.
     *
     * @return \Monolog\Handler\FilterHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/monolog/monolog/src/Monolog/Handler/FilterHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/monolog/monolog/src/Monolog/Handler/NullHandler.php';

        return $container->privates['monolog.handler.e_user_deprecated_filter'] = new \Monolog\Handler\FilterHandler(new \Monolog\Handler\NullHandler('DEBUG', true), ['info'], 'EMERGENCY', false);
    }
}
