<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderPdfServiceService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private 'Eccube\Service\OrderPdfService' shared autowired service.
     *
     * @return \Eccube\Service\OrderPdfService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/tecnickcom/tcpdf/tcpdf.php';
        include_once \dirname(__DIR__, 4).'/vendor/setasign/fpdi/src/FpdiTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/setasign/fpdi/src/Tcpdf/Fpdi.php';
        include_once \dirname(__DIR__, 4).'/src/Eccube/Service/OrderPdfService.php';

        return $container->privates['Eccube\\Service\\OrderPdfService'] = new \Eccube\Service\OrderPdfService(($container->services['Eccube\\Common\\EccubeConfig'] ?? self::getEccubeConfigService($container)), ($container->privates['Eccube\\Repository\\OrderRepository'] ?? self::getOrderRepositoryService($container)), ($container->privates['Eccube\\Repository\\ShippingRepository'] ?? $container->load('getShippingRepositoryService')), ($container->services['Eccube\\Service\\TaxRuleService'] ?? $container->load('getTaxRuleServiceService')), ($container->privates['Eccube\\Repository\\BaseInfoRepository'] ?? self::getBaseInfoRepositoryService($container)), ($container->privates['Eccube\\Twig\\Extension\\EccubeExtension'] ?? self::getEccubeExtensionService($container)), ($container->privates['Eccube\\Twig\\Extension\\TaxExtension'] ?? self::getTaxExtensionService($container)));
    }
}
