<?php

namespace ContainerXhVx8uS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPluginApiServiceService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private 'Eccube\Service\PluginApiService' shared autowired service.
     *
     * @return \Eccube\Service\PluginApiService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Eccube/Service/PluginApiService.php';

        return $container->privates['Eccube\\Service\\PluginApiService'] = new \Eccube\Service\PluginApiService(($container->services['Eccube\\Common\\EccubeConfig'] ?? self::getEccubeConfigService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['Eccube\\Repository\\BaseInfoRepository'] ?? self::getBaseInfoRepositoryService($container)), ($container->services['Eccube\\Repository\\PluginRepository'] ?? $container->load('getPluginRepositoryService')));
    }
}
