name: Deploy via Github Actions to Production
on:
    push:
        branches:
            - main
        tags:
            - "[0-9]+.[0-9]+.[0-9]*"

jobs:
    deploy:
        name: Deploy to server
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.1.0
              continue-on-error: true
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  server-dir: ${{ secrets.FTP_SERVER_DIR }}
                  dangerous-clean-slate: false
                  skip-cleanup-on-error: true
                  exclude: "[**/.**/**, .gitignore, **/.git/**, **/node_modules/**, **/vendor/**, .editorconfig, README.md, .phpcs.xml.dist, **.json, **.lock, postcss.config.js, **/src/**, var/**]"

            - name: Install lftp
              run: sudo apt-get install -y lftp

            - name: Deploy via FTP
              run: |
                lftp -c "
                set ftp:ssl-allow yes;
                open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }};
                mirror --reverse --continue --delete --exclude-glob var/** ./ ${{ secrets.FTP_SERVER_DIR }};
                bye;
                "



#test15