name: Deploy via Github Actions to Production
on:
    push:
        branches:
            - main
        tags:
            - "[0-9]+.[0-9]+.[0-9]*"

jobs:
    deploy:
        name: Deploy to server
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Sync files
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              continue-on-error: true
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  server-dir: ${{ secrets.FTP_SERVER_DIR }}
                  dangerous-clean-slate: false
                  # excludeを複数行で記載
                  exclude: |
                    **/.**/**
                    .gitignore
                    **/.git/**
                    **/node_modules/**
                    **/vendor/**
                    .editorconfig
                    README.md
                    .phpcs.xml.dist
                    **.json
                    **.lock
                    postcss.config.js
                    **/src/**
                    var/**
# deploytesttt